from datetime import datetime

from dislocations import *
import wurtzite as wzt
from visualization import plot_displacement
import math
from pathlib import Path

# INITIAL CONFIGURATION CONFIGURATION.
l0 = wzt.generate.create_lattice(
    dimensions=(19, 13, 1),  # (nx, ny, nz)
    cell="B4_GaN",
)

# PARAMETERS.
# Number of integration points.
n_points = 300
# Number of iterations
n_iters = 1

# Display parameters
# If True, the current configuration will be displayed after each dislocation
# is inserted.
# Otherwise, the current dislocation is only saved to the {name}_{timestamp}.svg
# file.
show_img = True
# OX limits [A]
xlim = (-25, 60)
# OY limits [A]
ylim = (-5, 45)
# Figure size [inches]
figsize = (15, 7.5)
# Glide plane line width [pints]
linewidth = 2.5
# Glide plane length (how far should be the glide plane calcualted).
gp_offset = 30

# offset_0: The offset that will be added to the position of each
# dislocation.
# The purpose of the offset was to move all the dislocations to satisfy
# requirements for the figures generated in the target article,
# i.e. two unit cells margin at the top, etc.
ny = 2
ox = l0.cell.dimensions[1]*0.5
oy = l0.cell.dimensions[1]*math.sqrt(3)/2
offset_0 = np.asarray([2*l0.cell.dimensions[0] + ox, oy, 0])

# Filename prefix (will be prepended to all filenames generated by this script).
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
filename_prefix = f"{Path(__file__).stem}_{timestamp}"

# ------------------------------------------ FIRST DISLOCATION
d1 = wzt.model.DislocationDef(
    # Burger's vector
    b=[1, 0, 0],
    # dislocation core position
    position=[3.190+0.8+6*l0.cell.dimensions[0], 10, 7.5] + offset_0,
    # dislocation plane
    plane=(0, 0, 1),
    # dislocation label (only for the presentation purpose)
    label="$d_1$",
    # dislocation tee color (only for the presentation purpose)
    color="brown"
)

# Calculate displacement + auxiliary information
log0 = displace(
    crystal=l0,
    dislocations=[],
    d_n=d1,
    n_iters=1,
    n_points=n_points,
)

# Translate atoms.
u0 = log0.last_u_atoms
last_d_state = log0.last_d_state
l1 = l0.translate(u0)
l1 = wzt.generate.update_bonds(l1, tolerance=0.45)

# Draw atoms.
fig, ax = wzt.visualization.plot_atoms_2d(l1, xlim=xlim, ylim=ylim, figsize=figsize)
# Draw tees.
for d in last_d_state.ds:
    wzt.visualization.display_tee_2d(ax, d, scale=0.5, cell=l0.cell)

# Save to the output file
filename = f"{filename_prefix}_dislocation1.svg"
fig.savefig(filename)
if show_img:
    plt.show()
print(f"Image saved to {filename}")
