from datetime import datetime

from dislocations import *
import wurtzite as wzt
import math
from pathlib import Path
import numpy as np

np.seterr(invalid="raise")

# INITIAL CONFIGURATION CONFIGURATION.
l0 = wzt.generate.create_lattice(
    dimensions=(19, 13, 1),  # (nx, ny, nz)
    cell="B4_GaN",
)

# PARAMETERS.
# Number of integration points.
n_points = 300
# Number of iterations
n_iters = 1

# Display parameters
# If True, the current configuration will be displayed after each dislocation
# is inserted.
# Otherwise, the current dislocation is only saved to the {name}_{timestamp}.svg
# file.
show_img = True
# OX limits [A]
xlim = (-25, 60)
# OY limits [A]
ylim = (-5, 45)
# Figure size [inches]
figsize = (15, 7.5)
# Glide plane line width [pints]
linewidth = 2.5
# Glide plane length (how far should be the glide plane calcualted).
gp_offset = 30

# offset_0: The offset that will be added to the position of each
# dislocation.
# The purpose of the offset was to move all the dislocations to satisfy
# requirements for the figures generated in the target article,
# i.e. two unit cells margin at the top, etc.
ny = 2
ox = l0.cell.dimensions[1] * 0.5
oy = l0.cell.dimensions[1] * math.sqrt(3) / 2
offset_0 = np.asarray([2 * l0.cell.dimensions[0] + ox, oy, 0])

# Filename prefix (will be prepended to all filenames generated by this script).
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
filename_prefix = f"6_dislocations_{timestamp}"

dislocations = [
    wzt.model.DislocationDef(
        # dislocation label (only for the presentation purpose)
        label="$d_1$",
        # Burger's vector
        b=[1, 0, 0],
        # dislocation core position
        position=[3.190 + 0.8 + 6 * l0.cell.dimensions[0], 10, 7.5] + offset_0,
        # dislocation plane
        plane=(0, 0, 1),
        # dislocation tee color (only for the presentation purpose)
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_2$",
        b=[1, 0, 0],
        position=[2.35, 9.66, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_3$",
        b=[0, 1, 0],
        position=[8.53, 17.61, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_4$",
        b=[1, 0, 0],
        position=[2.82, 21.54, 0],
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_5$",
        b=[1, 1, 0],
        position=[18.57, 18.92, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_6$",
        b=[0, -1, 0],
        position=[14.01, 4.74, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    )
]
debug_plots = {0, 5}

l = l0
current_dislocations = []

for i, d in enumerate(dislocations):
    print(f"------------------------------------------ DISLOCATION: {i}")
    # Calculate displacement + auxiliary information
    log = displace(
        crystal=l,
        dislocations=current_dislocations,
        d_n=d,
        n_iters=n_iters,
        n_points=n_points,
        plot_local=(i in debug_plots)
    )
    # Displacement.
    u = log.last_u_atoms
    # Log of the last state (where dislocations are located, glide planes, etc.)
    last_d_state = log.last_d_state
    current_dislocations = last_d_state.ds
    # Translate current lattice according to the displace.
    l = l.translate(u)
    # Update bonds between atoms.
    l = wzt.generate.update_bonds(l, tolerance=0.55)
    # Draw atoms.
    fig, ax = wzt.visualization.plot_atoms_2d(l, xlim=xlim, ylim=ylim, figsize=figsize)
    # Draw tees.
    for d in current_dislocations:
        wzt.visualization.display_tee_2d(ax, d, scale=0.5)

    # Save to the output file
    filename = f"{filename_prefix}_dislocation_{i}.svg"
    fig.savefig(filename)
    # Show image, if enabled.
    if show_img:
        plt.show()
    print(f"Image saved to {filename}")
