import pickle
from datetime import datetime

from dislocations import *
import wurtzite as wzt
import math
from pathlib import Path
import numpy as np
import params

np.seterr(invalid="raise")

# INITIAL CONFIGURATION CONFIGURATION.
l0 = wzt.generate.create_lattice(
    dimensions=(19, 13, 1),  # (nx, ny, nz)
    cell="B4_GaN",
)

# PARAMETERS.
# Number of integration points.
n_points = 1000
# Maximum number of iterations of the scheme solving Eq. (29).
n_iters = 20
# Method used to solve Eq. (29) for the positions of the dislocations already
# inserted into the lattice:
# - "newton": the modified Newton-Raphson scheme, Eqs. (30)-(33),
# - "picard": successive substitution.
method = "newton"
# Relaxation (multiplicity) factor of the Newton-Raphson corrections.
alpha = 0.6
# Convergence criterion [A]: stop as soon as max_d ||Delta x_d|| < tol.
tol = 1e-3

# Display parameters
# If True, the current configuration will be displayed after each dislocation
# is inserted.
# Otherwise, the current dislocation is only saved to the {name}_{timestamp}.svg
# file.
show_img = True
# Field of view: the OX/OY limits are derived from the bounding box of the
# dislocation cores (see `xlim`/`ylim` below), so that the figures show the
# neighbourhood of the dislocations instead of the whole -- mostly undistorted
# -- crystal. `fov_margin` is the margin left around the outermost cores [A].
fov_margin = 10.0
# Width of the figure [inches]; the height is derived from the field of view,
# so that the aspect ratio of the figure matches the aspect ratio of the data
# (plot_atoms_2d draws with aspect="equal").
fig_width = 12.0
# Glide plane line width [points]
linewidth = 2.5
# Glide plane color
gp_color = "tab:blue"
# The glide plane is not drawn closer than this [A] to any dislocation core:
# there the two lips of the cut merge, the displacement carried onto the
# polyline stops being meaningful and the line kinks (see clip_glide_plane).
gp_core_radius = 4.0

# offset_0: The offset that will be added to the position of each
# dislocation.
# The purpose of the offset was to move all the dislocations to satisfy
# requirements for the figures generated in the target article,
# i.e. two unit cells margin at the top, etc.
ny = 2
ox = l0.cell.dimensions[1] * 0.5
oy = l0.cell.dimensions[1] * math.sqrt(3) / 2
offset_0 = np.asarray([2 * l0.cell.dimensions[0] + ox, oy, 0])

# Filename prefix (will be prepended to all filenames generated by this script).
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
filename_prefix = f"6_dislocations_{timestamp}"

dislocations = [
    wzt.model.DislocationDef(
        # dislocation label (only for the presentation purpose)
        label="$d_1$",
        # Burger's vector
        b=[1, 0, 0],
        # dislocation core position
        position=[3.190 + 0.8 + 6 * l0.cell.dimensions[0], 10, 7.5] + offset_0,
        # dislocation plane
        plane=(0, 0, 1),
        # dislocation tee color (only for the presentation purpose)
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_2$",
        b=[1, 0, 0],
        position=[2.35, 9.66, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_3$",
        b=[0, 1, 0],
        position=[8.53, 17.61, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_4$",
        b=[1, 0, 0],
        position=[2.82, 21.54, 0],
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_5$",
        b=[1, 1, 0],
        position=[18.57, 18.92, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    ),
    wzt.model.DislocationDef(
        label="$d_6$",
        b=[0, -1, 0],
        position=[14.01, 4.74, 0] + offset_0,
        plane=(0, 0, 1),
        color="brown"
    )
]
# Numbers of the dislocations for which the (interactive, and quite expensive)
# diagnostic plots of the beta field and the glide planes should be displayed,
# e.g. {5}. Empty set = batch run.
debug_plots = set()

# Field of view: the bounding box of the dislocation cores, extended by
# `fov_margin` and clipped to the extent of the crystal (so that no vacuum is
# shown around the lattice).
_cores = np.stack([np.asarray(d.position, dtype=float) for d in dislocations])
_atoms = np.asarray(l0.coordinates, dtype=float)
xlim = (max(_cores[:, 0].min() - fov_margin, _atoms[:, 0].min()),
        min(_cores[:, 0].max() + fov_margin, _atoms[:, 0].max()))
ylim = (max(_cores[:, 1].min() - fov_margin, _atoms[:, 1].min()),
        min(_cores[:, 1].max() + fov_margin, _atoms[:, 1].max()))
# Keep the figure aspect ratio equal to the aspect ratio of the field of view.
figsize = (fig_width,
           fig_width * (ylim[1] - ylim[0]) / (xlim[1] - xlim[0]))
print(f"Field of view: xlim={xlim}, ylim={ylim}, figsize={figsize}")


def clip_glide_plane(glide_plane, coordinates, cores, atom_cutoff=2.0,
                     core_radius=4.0, min_vertices=5):
    """
    Selects the parts of the glide plane polyline that are worth drawing, and
    returns them as a list of separate polylines.

    Two parts are dropped:

    1. Everything outside the crystal. `find_glide_plane` integrates the glide
       plane over a fixed margin (`glide_plane_margin`) expressed in the local
       coordinate system of the dislocation, without any reference to the extent
       of the lattice. Because `create_lattice` produces a skewed (parallelogram)
       slab, the boundary of the crystal at the height of the glide plane depends
       on the dislocation, and the fixed margin overshoots it -- the line would
       be drawn over the vacuum next to the lattice. Vertices further than
       `atom_cutoff` [A] from any atom are dropped.

    2. Everything closer than `core_radius` [A] to a dislocation core.
       `displace_glide_plane` carries the polyline into the current configuration
       by averaging the displacements of the atoms just above and just below the
       cut. Close to a core the two lips of the cut merge, that average stops
       being meaningful, and the polyline visibly kinks (up to ~40 deg, whereas
       the polyline coming out of the ODE is smooth to within 0.4 deg). The core
       is also exactly where the continuum description does not apply, so the
       glide plane is simply not drawn there.

    The polyline may be cut into several pieces -- it is dropped near EVERY core,
    not only near the core of its own dislocation -- hence a list is returned.
    Pieces shorter than `min_vertices` vertices are discarded.
    """
    p = np.asarray(glide_plane)
    p = p.reshape(-1, p.shape[-1])
    xy = np.asarray(coordinates)[:, :2]
    cores = np.asarray(cores, dtype=float)[:, :2]

    to_atom = np.min(
        np.linalg.norm(p[:, None, :2] - xy[None, :, :], axis=2), axis=1)
    to_core = np.min(
        np.linalg.norm(p[:, None, :2] - cores[None], axis=2), axis=1)
    keep = (to_atom <= atom_cutoff) & (to_core >= core_radius)

    segments = []
    start = None
    for i, flag in enumerate(np.append(keep, False)):
        if flag and start is None:
            start = i
        elif not flag and start is not None:
            if i - start >= min_vertices:
                segments.append(p[start:i])
            start = None
    return segments


def main(params):
    current_state = params.get("init_state")
    start_dislocation = params.get("start_dislocation")
    is_save_state = not params.get("skip_save_state")

    if not current_state:
        # We start from the perfect configuration
        l = l0  # Current lattice
        current_dislocations = []  # Dislocations already applied
        n_ready_dislocations = 0
    else:
        # Start from the state read from the .pkl file
        l = current_state["l"][start_dislocation]  # Current lattice
        # Dislocations already applied
        current_dislocations = current_state["dislocations"][start_dislocation]
        # Number of dislocations already applied. For example, if already
        n_ready_dislocations = len(current_dislocations)

    ls = []
    all_dislocation_states = []
    all_convergence = []
    all_glide_planes = []

    for i in range(n_ready_dislocations, len(dislocations)):
        d = dislocations[i]
        print(f"------------------------------------------ DISLOCATION: {i+1}")
        # Calculate displacement + auxiliary information
        log = displace(
            crystal=l,
            dislocations=current_dislocations,
            d_n=d,
            n_iters=n_iters,
            n_points=n_points,
            method=method,
            alpha=alpha,
            tol=tol,
            plot_local=(i in debug_plots),
            plot_local_planes=(i in debug_plots)
        )
        all_convergence.append(log.convergence)
        # Displacement.
        u = log.last_u_atoms
        # Log of the last state
        # (where dislocations are located, glide planes, etc.)
        last_d_state = log.last_d_state
        current_dislocations = last_d_state.ds
        # Translate current lattice according to the displace.
        l = l.translate(u)
        # Update bonds between atoms.
        l = wzt.generate.update_bonds(l, tolerance=0.55)
        # Draw atoms.
        fig, ax = wzt.visualization.plot_atoms_2d(l, xlim=xlim, ylim=ylim, figsize=figsize)
        # Draw tees.
        for d in current_dislocations:
            wzt.visualization.display_tee_2d(ax, d, scale=0.5)

        # The glide plane carried into the configuration that is actually drawn
        # (i.e. after the current dislocation has been inserted).
        cores = [d.position for d in current_dislocations]
        segments = clip_glide_plane(log.last_glide_planes_displaced[-1],
                                    l.coordinates, cores,
                                    core_radius=gp_core_radius)
        all_glide_planes.append(segments)
        for p in segments:
            ax.plot(p[:, 0], p[:, 1], color=gp_color, linewidth=linewidth)

        # Save to the image files (.svg for viewing, .pdf ready to be included
        # in the LaTeX sources of the paper).
        for extension in ("svg", "pdf"):
            filename = f"{filename_prefix}_dislocation_{i}.{extension}"
            fig.savefig(filename, bbox_inches="tight")
            print(f"Image saved to {filename}")
        # Show image, if enabled.
        if show_img:
            plt.show()

        ls.append(l)
        all_dislocation_states.append(current_dislocations)

    print("Convergence history (max||Psi|| [A], max||dx|| [A]) per dislocation:")
    for i, c in enumerate(all_convergence, start=n_ready_dislocations + 1):
        print(f"  dislocation {i}: {c}")

    if is_save_state:
        with open(f"state_{timestamp}.pkl", "wb") as f:
            state = {
                "l": ls,
                "dislocations": all_dislocation_states,
                "convergence": all_convergence,
                # The glide plane of the dislocation inserted as the last one,
                # as drawn in the figures (clipped to the crystal).
                "glide_planes": all_glide_planes,
                "method": method,
                "n_points": n_points,
                "alpha": alpha,
                "tol": tol,
            }
            pickle.dump(state, f)


if __name__ == "__main__":
    default_params = params.read_default_params()
    main(default_params)
